export enum ACTION_TYPES {
  SET_AUTHENTICATED = "SET_AUTHENTICATED",
  SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED",
  SET_USER = "SET_USER",
  LOADING_USER = "LOADING_USER",

  SET_ERRORS = "SET_ERRORS",
  LOADING_UI = "LOADING_UI",
  CLEAR_ERRORS = "CLEAR_ERRORS",
}
